### ISSUE TITLE
Error on init

### ISSUE THREAD

**Issue by Hirbod** [markmarijnissen/cordova-file-cache#1]
Hi,

thanks for your lib. Looks very promising. 
I have a problem on init and don't know how to solve it:

TypeError: undefined is not an object (evaluating 'options.Promise')
CrodovaPromiseFS.js line 90.

What I'm doing wrong?

```js
        /* Cache */
        var cache = CordovaFileCache({
          fs: CordovaPromiseFS(),
          mode: 'hash', // or 'mirror'
          localRoot: 'data',
          cacheBuster: false 
        });

        cache.ready.then(function(list){
            // Promise when cache is ready.
            // Returns a list of paths on the FileSystem that are cached.
            console.log('cache is ready');
            console.log(list);
        });
```

This is what I'm calling

**Comment by Hirbod** [comment]
Awesome library, but you really need to look at your documentation.

After I did this changes:
```
        /* Cache */
        var cache = new CordovaFileCache({
            fs: CordovaPromiseFS({ 
                persistent: false,
                Promise: window.Promise 
            }),
            mode: 'hash', // or 'mirror'
            localRoot: 'data',
            cacheBuster: false 
        });

       cache.ready.then(function(list){
            console.log('cache is ready');
            console.log(list);
        });
```

it start to work. You forgot to write "new..." and you did not mention that CordovaPromiseFS() isn't optional. And please, define some Promise libs. Tried Q.Prmoise but decided to use "window.Promise", cause angular.js is active. Actually, your lib should detect this automatically, and as I can see, you tried, but something isn't working.

And also, in your Promise README, you forget one , in your example.

Really lovely work but please consider to make your documentations clener and more understandable as there are a bunch of users they will not get the rid of this for sure. Tooked me 2 hours to get your lib work. Nontheless, seems to work perfectly. Just need to figure out how to store data in TEMPORARY instead of "data".

**Comment by markmarijnissen** [comment]
* I've updated documentation. It mentions the `new` keyword and also mentions the required `Promise`.
* Thanks for the chaining suggestion, but I don't understand how this would work. Please read the method signatures. You either use `get(xxx)` or `toInternalURL(xxx)`. They return Promises - which are already chainable.
