### ISSUE TITLE
Uncaught (in promise) FileError {code: 12}

### ISSUE THREAD

**Issue by josh-m-sharpe** [markmarijnissen/cordova-file-cache#10]
I got this plugin working for iOS and everything works great.  Thanks!

I then went over to the android side, and I'm getting this javascript error when the app loads:
```
Uncaught (in promise) FileError {code: 12}
```
...no backtrace - that's really it.

The changes I made to cordova.xml were simply adding this:
```
<plugin name="cordova-plugin-file" spec="~4.1.1" />
<plugin name="cordova-plugin-file-transfer" spec="~1.5.0" />
<preference name="AndroidPersistentFileLocation" value="Compatibility" />
```

JS libs added:
```
<script type="text/javascript" src="js/lib/CordovaPromiseFS.js" defer></script>
<script type="text/javascript" src="js/lib/CordovaFileCache.js" defer></script>
```

Initializing the cache like so:
```
new CordovaFileCache({
    fs: new CordovaPromiseFS({Promise: Promise}),
    serverRoot: $server_hostname + '/assets/',
    localRoot: 'data',
    cacheBuster: false
  })
```

...again, this all works perfectly on iOS, so this must be some concern of Android...?  Any help would be appreciated.  Thank you!

**Comment by josh-m-sharpe** [comment]
Screenshot of this error:
![image](https://cloud.githubusercontent.com/assets/14128624/14305774/c8af0bfc-fb8d-11e5-9c83-067134f1049e.png)

**Comment by josh-m-sharpe** [comment]
Looks like this method is throwing the FileError:

https://github.com/markmarijnissen/cordova-promise-fs/blob/master/dist/CordovaPromiseFS.js#L54

FileError code 12 is PATH_EXISTS_ERROR: https://developer.mozilla.org/en-US/docs/Web/API/FileError

...but if I change localRoot to 'datafoo' the error goes away.  Seems odd.

**Comment by josh-m-sharpe** [comment]
I think this was ultimately solved by installing and using bluebird.  Might be useful to have some check that the various Promise requirements are in place?  Not sure how that would work thought.

**Comment by markmarijnissen** [comment]
Given

* You have an old version of Cordova OR you set compatability mode in config.xml
* You are running Android (perhaps only on some Nexus devices?)
* You have no SD card

Then the fileSystem root will point to the root of internal storage, which already has a `data` folder reserved for other things. 

This will throw an error.
