### ISSUE TITLE
Compatibility issue on iOS < 8.1 and Android < 4.4.4

### ISSUE THREAD

**Issue by rmorandi** [markmarijnissen/cordova-file-cache#2]
This plugin make use of Promises, that are part of ECMAScript 6 and are still unstable.

https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility

http://caniuse.com/#feat=promises

You should add an important note about this.

**Comment by starquake** [comment]
It does not use ECMAScript 6 promises:

You need to include a Promise library when creating a CordovaPromiseFS. Any library that follows the A+ spec will work. For example: bluebird or promiscuous.

**Comment by markmarijnissen** [comment]
@rmorandi You're incorrect. Any library that follows the A+ spec will work, such as bluebird or promiscuous. This is explicitly mentioned in the readme.

Thanks @starquake

**Comment by rmorandi** [comment]
@markmarijnissen the issue was posted on 21/02 about the 0.10.0 version ;)

**Comment by markmarijnissen** [comment]
Ah, my bad! :)
