### ISSUE TITLE
License hidden

### ISSUE THREAD

**Issue by cbacko01** [markmarijnissen/cordova-file-cache#6]
Hi,

First of all, awesome plugin. I'm really excited to use it. 

I had to do some hunting before discovering the license in the bower and npm files, which list the license as MIT. Assuming that's your intended license, GitHub [advises](https://help.github.com/articles/open-source-licensing/) "to avoid any potential ambiguity, it's best to include the license file with your project as well." Seeing it spelled-out would make me feel a little more comfortable. 

(I believe this applies for cordova-promise-fs as well.)

Best,
Chris

**Comment by markmarijnissen** [comment]
Of course, no problem!

**Comment by cbacko01** [comment]
Awesome, thanks!
